spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
jwt:
  key: "가나다라마바사아자차카타파하1234567890987654321"
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

#  ${JWT_SECRET_KEY}