spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG


# ----- ${JWT_SECRET_KEY} -----
jwt:
  key: "가나다라마바사아자차카타파하1234567890987654321"
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420


# ----- email 인증 -----
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    display_name: 홍길동1
    email: gangtaegyeong12@gmail.com
    password: lxdqaavnbvpgidgr
    auth: true
    starttls:
      enable: true
  subject:
    user:
      registration: 가입을 축하합니다!
  template:
    name:
      user:
        join: email.registration-user